module.exports = [
  {
    section: "Access & gameplay",
    key: "force-gamemode",
    label: "Force game mode",
    type: "boolean",
    default: false,
    description:
      "Force the configured game mode for players, including after world creation.",
  },
  {
    section: "Access & gameplay",
    key: "online-mode",
    label: "Xbox Live authentication",
    type: "boolean",
    default: true,
    description: "Require connected players to authenticate with Xbox Live.",
  },
  {
    section: "Access & gameplay",
    key: "allow-list",
    label: "Require allow list",
    type: "boolean",
    default: false,
    description: "Only permit players listed in allowlist.json.",
  },
  {
    section: "Access & gameplay",
    key: "allow-player-joining",
    label: "Allow players to join",
    type: "boolean",
    default: true,
    description:
      "Permit normal player joins unless scripting explicitly allows them.",
  },
  {
    section: "Access & gameplay",
    key: "default-player-permission-level",
    label: "Default permission",
    type: "select",
    options: ["visitor", "member", "operator"],
    default: "member",
  },
  {
    section: "Access & gameplay",
    key: "texturepack-required",
    label: "Require texture packs",
    type: "boolean",
    default: false,
  },
  {
    section: "Access & gameplay",
    key: "chat-restriction",
    label: "Chat restriction",
    type: "select",
    options: ["None", "Dropped", "Disabled"],
    default: "None",
  },
  {
    section: "Access & gameplay",
    key: "disable-player-interaction",
    label: "Disable player interaction",
    type: "boolean",
    default: false,
  },

  {
    section: "World & performance",
    key: "view-distance",
    label: "View distance",
    type: "integer",
    min: 5,
    default: 32,
    description: "Maximum view distance in chunks.",
  },
  {
    section: "World & performance",
    key: "tick-distance",
    label: "Tick distance",
    type: "integer",
    min: 4,
    max: 12,
    default: 4,
  },
  {
    section: "World & performance",
    key: "player-idle-timeout",
    label: "Idle timeout (minutes)",
    type: "integer",
    min: 0,
    default: 30,
  },
  {
    section: "World & performance",
    key: "max-threads",
    label: "Maximum threads",
    type: "integer",
    min: 0,
    default: 8,
    description: "Use 0 to let Bedrock use all available threads.",
  },
  {
    section: "World & performance",
    key: "client-side-chunk-generation-enabled",
    label: "Client-side chunk generation",
    type: "boolean",
    default: true,
  },
  {
    section: "World & performance",
    key: "server-build-radius-ratio",
    label: "Server build radius ratio",
    type: "text",
    default: "Disabled",
    description: "Disabled or a decimal from 0.0 to 1.0.",
  },

  {
    section: "Network",
    key: "transport",
    label: "Transport",
    type: "select",
    options: ["raknet", "nethernet"],
    default: "raknet",
  },
  {
    section: "Network",
    key: "enable-lan-visibility",
    label: "Direct LAN visibility",
    type: "boolean",
    default: false,
    description:
      "Keep disabled when the BedrockConnect gateway owns the LAN discovery port.",
  },
  {
    section: "Network",
    key: "server-ip",
    label: "Bind IP",
    type: "text",
    default: "",
    description: "Optional IP literal. Ignored with RakNet.",
  },
  {
    section: "Network",
    key: "server-udp-ports",
    label: "NetherNet UDP mappings",
    type: "text",
    default: "",
    description:
      "Comma-separated internal ranges or external-to-internal mappings.",
  },
  {
    section: "Network",
    key: "compression-threshold",
    label: "Compression threshold",
    type: "integer",
    min: 0,
    max: 65535,
    default: 1,
  },
  {
    section: "Network",
    key: "compression-algorithm",
    label: "Compression algorithm",
    type: "select",
    options: ["zlib", "snappy"],
    default: "zlib",
  },

  {
    section: "Content & logging",
    key: "content-log-file-enabled",
    label: "Content log file",
    type: "boolean",
    default: false,
  },
  {
    section: "Content & logging",
    key: "content-log-console-output-enabled",
    label: "Content errors in console",
    type: "boolean",
    default: false,
  },
  {
    section: "Content & logging",
    key: "content-log-level",
    label: "Content log level",
    type: "select",
    options: ["error", "warning", "info", "verbose"],
    default: "info",
  },
  {
    section: "Content & logging",
    key: "block-network-ids-are-hashes",
    label: "Stable hashed block IDs",
    type: "boolean",
    default: true,
  },
  {
    section: "Content & logging",
    key: "disable-persona",
    label: "Disable persona",
    type: "boolean",
    default: false,
  },
  {
    section: "Content & logging",
    key: "disable-custom-skins",
    label: "Disable custom skins",
    type: "boolean",
    default: false,
  },
  {
    section: "Content & logging",
    key: "disable-client-vibrant-visuals",
    label: "Disable Vibrant Visuals",
    type: "boolean",
    default: true,
  },

  {
    section: "Authority & anti-cheat",
    key: "server-authoritative-movement-strict",
    label: "Strict authoritative movement",
    type: "boolean",
    default: false,
  },
  {
    section: "Authority & anti-cheat",
    key: "server-authoritative-dismount-strict",
    label: "Strict dismount validation",
    type: "boolean",
    default: false,
  },
  {
    section: "Authority & anti-cheat",
    key: "server-authoritative-entity-interactions-strict",
    label: "Strict entity interactions",
    type: "boolean",
    default: false,
  },
  {
    section: "Authority & anti-cheat",
    key: "player-position-acceptance-threshold",
    label: "Position acceptance threshold",
    type: "number",
    min: 0,
    step: 0.01,
    default: 0.5,
  },
  {
    section: "Authority & anti-cheat",
    key: "player-movement-action-direction-threshold",
    label: "Action direction threshold",
    type: "number",
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.85,
  },
  {
    section: "Authority & anti-cheat",
    key: "server-authoritative-block-breaking-pick-range-scalar",
    label: "Block-breaking range scalar",
    type: "number",
    min: 0,
    step: 0.1,
    default: 1.5,
  },

  {
    section: "Script debugging",
    key: "allow-outbound-script-debugging",
    label: "Allow outbound debugging",
    type: "boolean",
    default: false,
  },
  {
    section: "Script debugging",
    key: "allow-inbound-script-debugging",
    label: "Allow inbound debugging",
    type: "boolean",
    default: false,
  },
  {
    section: "Script debugging",
    key: "force-inbound-debug-port",
    label: "Inbound debug port",
    type: "integer",
    min: 1,
    max: 65535,
    default: 19144,
  },
  {
    section: "Script debugging",
    key: "script-debugger-auto-attach",
    label: "Debugger auto-attach",
    type: "select",
    options: ["disabled", "connect", "listen"],
    default: "disabled",
  },
  {
    section: "Script debugging",
    key: "script-debugger-auto-attach-connect-address",
    label: "Debugger address",
    type: "text",
    default: "localhost:19144",
  },
  {
    section: "Script debugging",
    key: "script-debugger-auto-attach-timeout",
    label: "Attach timeout",
    type: "integer",
    min: 0,
    max: 10,
    default: 0,
  },
  {
    section: "Script debugging",
    key: "script-debugger-passcode",
    label: "Debugger passcode",
    type: "password",
    default: "",
  },

  {
    section: "Script watchdog",
    key: "script-watchdog-enable",
    label: "Enable watchdog",
    type: "boolean",
    default: true,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-enable-exception-handling",
    label: "Watchdog exception handling",
    type: "boolean",
    default: true,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-enable-shutdown",
    label: "Shutdown on unhandled watchdog event",
    type: "boolean",
    default: true,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-hang-exception",
    label: "Throw on script hang",
    type: "boolean",
    default: true,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-hang-threshold",
    label: "Hang threshold (ms)",
    type: "integer",
    min: 3000,
    max: 20000,
    default: 10000,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-spike-threshold",
    label: "Spike threshold (ms)",
    type: "integer",
    min: 50,
    max: 500,
    default: 100,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-slow-threshold",
    label: "Slow threshold (ms)",
    type: "integer",
    min: 5,
    max: 50,
    default: 10,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-memory-warning",
    label: "Memory warning (MB)",
    type: "integer",
    min: 0,
    max: 2000,
    default: 100,
  },
  {
    section: "Script watchdog",
    key: "script-watchdog-memory-limit",
    label: "Memory limit (MB)",
    type: "integer",
    min: 0,
    max: 2000,
    default: 250,
  },

  {
    section: "Diagnostics & editor",
    key: "diagnostics-capture-auto-start",
    label: "Auto-start diagnostics capture",
    type: "boolean",
    default: false,
  },
  {
    section: "Diagnostics & editor",
    key: "diagnostics-capture-max-files",
    label: "Maximum diagnostic files",
    type: "integer",
    min: 1,
    default: 5,
  },
  {
    section: "Diagnostics & editor",
    key: "diagnostics-capture-max-file-size",
    label: "Diagnostic file size (bytes)",
    type: "integer",
    min: 1,
    default: 2097152,
  },
  {
    section: "Diagnostics & editor",
    key: "sentry-rate-limit-window",
    label: "Sentry rate window (seconds)",
    type: "integer",
    min: 0,
    default: 60,
  },
  {
    section: "Diagnostics & editor",
    key: "sentry-max-events-per-window",
    label: "Sentry events per window",
    type: "integer",
    min: 0,
    default: 10,
  },
  {
    section: "Diagnostics & editor",
    key: "enable-profiler",
    label: "Enable profiler",
    type: "boolean",
    default: true,
  },
  {
    section: "Diagnostics & editor",
    key: "enable-editor-network-metrics",
    label: "Editor network metrics",
    type: "boolean",
    default: true,
  },
  {
    section: "Diagnostics & editor",
    key: "convert-world-to-editor-project",
    label: "Convert world to editor project",
    type: "boolean",
    default: false,
  },
];
